services:
  esphome:
    container_name: esphome
    image: esphome/esphome:latest
    volumes:
      - ./esphome:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6052:6052"
    devices:
      - "/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0:/dev/ttyUSB0"
    privileged: true
    restart: unless-stopped
